clusterGroup:
  name: prod
  isHubCluster: true

  namespaces:
    - inferencing-app
    - fraud-detection:
        labels:
          opendatahub.io/dashboard: true
          openshift.io/cluster-monitoring: true
    - redhat-ods-operator:
        operatorGroup: true
        targetNamespaces: []
    - openshift-serverless:
        operatorGroup: true
        targetNamespaces: []

  subscriptions:
    rhods:
      name: rhods-operator
      namespace: redhat-ods-operator

    servicemesh:
      name: servicemeshoperator
      namespace: openshift-operators

    serverless:
      name: serverless-operator
      namespace: openshift-serverless

  applications:
    rhods:
      name: rhods
      namespace: redhat-ods-operator
      path: charts/rhods

    inferencing-app:
      name: inferencing-app
      namespace: inferencing-app
      path: charts/inferencing-app

    minio:
      name: minio-storage
      namespace: fraud-detection
      path: charts/minio

    fraud-detection:
      name: fraud-detection
      namespace: fraud-detection
      path: charts/fraud-detection
